package gui;

import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import dao.DaoException;
import dao.DaoException;
import dao.NewInterface;
import dao.ProductDao;
import domain.Product;
import java.awt.Window;
import java.math.BigDecimal;
import java.util.Collection;
import javax.swing.JOptionPane;
import net.sf.oval.ConstraintViolation;
import net.sf.oval.Validator;
import net.sf.oval.exception.ConstraintsViolatedException;

/**
 *
 * @author alghu437
 */
public class Form extends javax.swing.JDialog {

    //private ProductDao dao = new ProductDao();
    
    ///////////////////lab6-dao////////////////
    private final NewInterface dao;
    
    private gui.helpers.SimpleListModel myModel = new gui.helpers.SimpleListModel();

    private Product product  = new Product();
    /**
     * Creates new form Form
     */
    
    ///////////////////lab6-dao////////////////
    public Form(java.awt.Frame parent, boolean modal, NewInterface dao) {
        super(parent);
         super.setModal(modal);
        initComponents();
        txtCategory.setEditable(true);
        this.dao = dao;
        txtCategory.setEditable(true);
        Collection<String> categories = dao.getCategories();
        myModel.updateItems(categories);
        txtCategory.setModel(myModel);
    }
    
   //////////////////////////////////////////bonus1
    public Form(Window parent, boolean modal, Product productToEdit, NewInterface productDao) {
        this(parent, modal,dao);
        
        this.product = productToEdit;
        this.setName("productDialog");
        txtID.setText(String.valueOf(productToEdit.getProductID()));
        //txtID.setValue(productToEdit.getProductID());
        txtName.setText(productToEdit.getName());
        txtDescription.setText(productToEdit.getDescription());
        txtCategory.setSelectedItem(productToEdit.getCategory());
        txtPrice.setText(String.valueOf(productToEdit.getListPrice()));
        txtQuantity.setText(String.valueOf(productToEdit.getQuantityStock()));
        //txtPrice.setValue(productToEdit.getListPrice());
        //txtQuantity.setValue(productToEdit.getQuantityStock());
        
        txtID.setEditable(false);
       
    }
///////////////////////////////////////////bonus1

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        txtID = new JTextField();
        jLabel3 = new JLabel();
        txtName = new JTextField();
        jLabel4 = new JLabel();
        jScrollPane1 = new JScrollPane();
        txtDescription = new JTextArea();
        jLabel5 = new JLabel();
        txtCategory = new JComboBox<>();
        jLabel6 = new JLabel();
        txtPrice = new JTextField();
        jLabel7 = new JLabel();
        txtQuantity = new JTextField();
        buttonSave = new JButton();
        buttonCancel = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setName("this");
        var contentPane = getContentPane();

        //---- jLabel1 ----
        jLabel1.setText("Product Editor");
        jLabel1.setName("jLabel1");

        //---- jLabel2 ----
        jLabel2.setText("ID");
        jLabel2.setName("jLabel2");

        //---- txtID ----
        txtID.setName("txtID");

        //---- jLabel3 ----
        jLabel3.setText("Name");
        jLabel3.setName("jLabel3");

        //---- txtName ----
        txtName.setName("txtName");

        //---- jLabel4 ----
        jLabel4.setText("Description");
        jLabel4.setName("jLabel4");

        //======== jScrollPane1 ========
        {
            jScrollPane1.setName("jScrollPane1");

            //---- txtDescription ----
            txtDescription.setColumns(20);
            txtDescription.setRows(5);
            txtDescription.setName("txtDescription");
            jScrollPane1.setViewportView(txtDescription);
        }

        //---- jLabel5 ----
        jLabel5.setText("Category");
        jLabel5.setName("jLabel5");

        //---- txtCategory ----
        txtCategory.setModel(new DefaultComboBoxModel<>(new String[] {
            "Item 1",
            "Item 2",
            "Item 3",
            "Item 4"
        }));
        txtCategory.setName("txtCategory");

        //---- jLabel6 ----
        jLabel6.setText("Price");
        jLabel6.setName("jLabel6");

        //---- txtPrice ----
        txtPrice.setName("txtPrice");

        //---- jLabel7 ----
        jLabel7.setText("Quantity in Stock");
        jLabel7.setName("jLabel7");

        //---- txtQuantity ----
        txtQuantity.setName("txtQuantity");

        //---- buttonSave ----
        buttonSave.setText("Save");
        buttonSave.setName("buttonSave");
        buttonSave.addActionListener(e -> buttonSaveActionPerformed(e));

        //---- buttonCancel ----
        buttonCancel.setText("Cancel");
        buttonCancel.setName("buttonCancel");
        buttonCancel.addActionListener(e -> buttonCancelActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtID, GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
                                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtName))
                                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 385, GroupLayout.PREFERRED_SIZE))
                                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCategory, GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
                                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPrice))
                                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtQuantity))))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(buttonSave)
                            .addGap(193, 193, 193)
                            .addComponent(buttonCancel)))
                    .addContainerGap(52, Short.MAX_VALUE))
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE)
                    .addGap(121, 121, 121))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel1)
                    .addGap(26, 26, 26)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtID, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtName, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
                    .addGap(57, 57, 57)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))
                    .addGap(52, 52, 52)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtCategory, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                    .addGap(39, 39, 39)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtPrice, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(txtQuantity, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSave)
                        .addComponent(buttonCancel))
                    .addContainerGap(35, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // ////////////////////////////////Lab6-1 number format exception
        try {
            String id = txtID.getText();
            String name = txtName.getText();
            String description = txtDescription.getText();
            String category = (String) txtCategory.getSelectedItem();
            String price = txtPrice.getText();
            BigDecimal priceBD = new BigDecimal(price);
            String quantity = txtQuantity.getText();
            BigDecimal quantityBD = new BigDecimal(quantity);

            Product p1 = new Product();
            p1.setProductID(id);
            p1.setName(name);
            p1.setDescription(description);
            p1.setCategory(category);
            p1.setListPrice(priceBD);
            p1.setQuantityStock(quantityBD);

  ////////////////////Lab6-5:add code          /////////////////////
            new Validator().assertValid(p1);
            //////
            dao.saveProduct(p1);
            this.dispose();
            System.out.println(p1);
// ////////////////////////////////Lab6- number format exception
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,
                    "You have entered a price or quantity that is not a valid number.",
                    "Input Error", JOptionPane.ERROR_MESSAGE);}

        
    ////////////////////////Lab 6 -6:ConstraintsViolatedException.
       catch (ConstraintsViolatedException ex) {
         // get the violated constraints from the exception
         ConstraintViolation[] violations = ex.getConstraintViolations();
         // create a nice error message for the user
         String msg = "Please fix the following input problems:";
         for (ConstraintViolation cv : violations) {
           msg += "\n •" + cv.getMessage();
         }
         // display the message to the user
         JOptionPane.showMessageDialog(this, msg, "Input Error",
            JOptionPane.ERROR_MESSAGE);
}
   ///////////////////////////lab6-exercise4-3: add dao exception 
    catch(DaoException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }

    //GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
            //</editor-fold>
            
		//</editor-fold>

		/* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form dialog = new Form(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JTextField txtID;
    private JLabel jLabel3;
    private JTextField txtName;
    private JLabel jLabel4;
    private JScrollPane jScrollPane1;
    private JTextArea txtDescription;
    private JLabel jLabel5;
    private JComboBox<String> txtCategory;
    private JLabel jLabel6;
    private JTextField txtPrice;
    private JLabel jLabel7;
    private JTextField txtQuantity;
    private JButton buttonSave;
    private JButton buttonCancel;
    // End of variables declaration//GEN-END:variables
}

