package gui;

import dao.NewInterface;

/**
 *
 * @author alghu437
 */
public class MainMenu extends javax.swing.JFrame {
    ///////////////////lab6-dao////////////////
    private final NewInterface dao; 
    ///////////////////lab6-dao////////////////
	/**
	 * Creates new form MainMenu
	 */
    
    ///////////////////lab6-dao////////////////
	public MainMenu(NewInterface dao) {
		initComponents();
                this.dao=dao;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      buttonViewProduct = new javax.swing.JButton();
      buttonExit = new javax.swing.JButton();
      buttonAddNewProduct = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setText("Product Administration");
      jLabel1.setName("jLabel1"); // NOI18N

      buttonViewProduct.setText("View Products");
      buttonViewProduct.setName("buttonViewProduct"); // NOI18N
      buttonViewProduct.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonViewProductActionPerformed(evt);
         }
      });

      buttonExit.setText("Exit");
      buttonExit.setName("buttonExit"); // NOI18N
      buttonExit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonExitActionPerformed(evt);
         }
      });

      buttonAddNewProduct.setText("Add a New Product");
      buttonAddNewProduct.setName("buttonAddNewProduct"); // NOI18N
      buttonAddNewProduct.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonAddNewProductActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(95, 95, 95)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(buttonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                     .addComponent(buttonViewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                     .addComponent(buttonAddNewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(138, 138, 138)
                  .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                  .addGap(41, 41, 41)))
            .addGap(87, 87, 87))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addGap(40, 40, 40)
            .addComponent(buttonAddNewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
            .addGap(46, 46, 46)
            .addComponent(buttonViewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
            .addGap(40, 40, 40)
            .addComponent(buttonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
            .addGap(77, 77, 77))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
		// TODO add your handling code here:
		System.exit(0);
   }//GEN-LAST:event_buttonExitActionPerformed

   private void buttonAddNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddNewProductActionPerformed
		// TODO add your handling code here:
		Form product = new Form(this, true,this.dao);
		product.setLocationRelativeTo(this);
		product.setVisible(true);
   }//GEN-LAST:event_buttonAddNewProductActionPerformed

   private void buttonViewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewProductActionPerformed
		// TODO add your handling code here:
///////////////////lab6-dao////////////////
		ProductViewer product = new ProductViewer(this, true,dao);
///////////////////lab6-dao////////////////               
		product.setLocationRelativeTo(this);
		product.setVisible(true);
   }//GEN-LAST:event_buttonViewProductActionPerformed

	/**
	 * @param args the command line arguments
	 */
	/*public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		/*try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>*/

		/* Create and display the form */
		/*java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainMenu().setVisible(true);
			}
		});
	}*/

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton buttonAddNewProduct;
   private javax.swing.JButton buttonExit;
   private javax.swing.JButton buttonViewProduct;
   private javax.swing.JLabel jLabel1;
   // End of variables declaration//GEN-END:variables
}
