package gui;

import dao.NewInterface;
import dao.ProductDao;
import domain.Product;
import gui.helpers.SimpleListModel;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author alghu437
 */
public class ProductViewer extends javax.swing.JDialog {

	//private ProductDao dao = new ProductDao();
///////////////////lab6-dao////////////////
    private NewInterface dao;
 ///////////////////lab6-dao////////////////   
	SimpleListModel myModel = new SimpleListModel();

	/**
	 * Creates new form ProductViewer
	 */
        ///////////////////lab6-dao////////////////
	public ProductViewer(java.awt.Frame parent, boolean modal, NewInterface dao) {
		super(parent, modal);
		initComponents();
txtCategory.setEditable(true);
this.dao=dao;
        SimpleListModel newModel = new SimpleListModel();
        Collection<String> categories = dao.getCategories();
		Collection<Product> products = dao.getProducts();
		myModel.updateItems(products);
		productsList.setModel(myModel);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsList = new javax.swing.JList<>();
        buttonClose = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("View Products");
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        productsList.setName("productsList"); // NOI18N
        jScrollPane1.setViewportView(productsList);

        buttonClose.setText("Close");
        buttonClose.setName("buttonClose"); // NOI18N
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.setName("buttonDelete"); // NOI18N
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("Search");
        jLabel2.setName("jLabel2"); // NOI18N

        txtSearch.setName("txtSearch"); // NOI18N

        buttonSearch.setText("Search");
        buttonSearch.setName("buttonSearch"); // NOI18N
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Category Filter");
        jLabel3.setName("jLabel3"); // NOI18N

        txtCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        txtCategory.setName("txtCategory"); // NOI18N
        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
		this.dispose();
		// TODO add your handling code here:
   }//GEN-LAST:event_buttonCloseActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
       /* if (productsList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "please select a product first", "warnings",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            int result = JOptionPane.showMessageDialog(this, "are you sure delete", "confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
        if (result == JOptionPane.YES_OPTION){
        
        domain.Product p1=(domain.Product) productsList.getSelectedValue();
        dao.deleteProduct(p1);
        Collection<domain.Product> p2=dao.getProducts();
        myModel.updateItems(p1);
        productsList.setModel(myModel);*/
               domain.Product product = (domain.Product)productsList.getSelectedValue();

        if(productsList.isSelectionEmpty()){

            JOptionPane.showMessageDialog(this, "Please select a Product before deleting!", "Warning", JOptionPane.INFORMATION_MESSAGE);

        }else{

            int result = JOptionPane.showConfirmDialog(this, "Are you sure you wish to delete?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);

            if (result == JOptionPane.YES_OPTION) {

                dao.deleteProduct(product);

                Collection<domain.Product> products = dao.getProducts();

                myModel.updateItems(products);

                productsList.setModel(myModel);

            }

        }
        
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        
        String id = txtSearch.getText();

        if(id == null){

            JOptionPane.showMessageDialog(this, "Please enter an ID to search!", "Warning", JOptionPane.WARNING_MESSAGE);

            return;

        }
         int idInt=Integer.parseInt(id);
        Product p = dao.getProductById(idInt);

        myModel.updateItems(p);

        productsList.setModel(myModel);

        
    }//GEN-LAST:event_buttonSearchActionPerformed
  
//////////////////////////////bonus1/////////  
    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        Product product = (Product)productsList.getSelectedValue();

        if(productsList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Please select a Product before editing!", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }else{
            Form dialog = new Form (this, true, product, this.dao);

            // centre the dialog on the parent window
            dialog.setLocationRelativeTo(this);

            // make the dialog visible
            dialog.setVisible(true);

            //will only run after dialog is closed
            Collection<domain.Product> products = dao.getProducts();
            myModel.updateItems(products);
            productsList.setModel(myModel);
        }
    }
///////////////////////////////////bonus1////////////

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        // TODO add your handling code here:
        
        
        String category = (String)txtCategory.getSelectedItem();

        Collection<Product> filteredProducts = dao.filterByCategory(category);

        myModel.updateItems(filteredProducts);

        productsList.setModel(myModel);
    }//GEN-LAST:event_txtCategoryActionPerformed

	/**
	 * @param args the command line arguments
	 */
	/*public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		/*try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ProductViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ProductViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ProductViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ProductViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>*/

		/* Create and display the dialog */
		/*java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ProductViewer dialog = new ProductViewer(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Product> productsList;
    private javax.swing.JComboBox<String> txtCategory;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
