@startuml
' use strict UML mode
skinparam style strictuml

' create actor user
actor "User" as user

' create main adminstration 
participant "Administration" as main <<main>>
main++

' create main menu frame
create "MainMenu" as menu <<frame>>
main -> menu : construct

user -> menu++ : clicks 'View Products' button

' create product viewer dialog
create "ProductViewer" as viewer <<dialog>>
menu -> viewer :  construct(this, true)

viewer++

' create a DAO
create "ProductDatabase" as dao <<DAO>>
viewer -> dao : construct 

' create the simple model list
create "SimpleListModel" as modellist <<gui.helpers>>
viewer -> modellist : construct



' get the products from dao database
viewer -> dao++ : getProducts()

create "JdbcConnection" as jdbc <<DAO>>
dao -> jdbc++ : getConnection(dbURL)
jdbc --> dao : connection
jdbc--

dao --> viewer : allProducts
dao--

' put products in Simple List Model
viewer -> modellist++ : updateItems(allProducts)
modellist--

' update list to display products
viewer -> viewer : setModel(productDisplay)
viewer--

viewer --> user

' Pull out selected product to edit
user -> viewer++ : enters ID in search field
viewer--
user -> viewer++ : clicks 'Search' button

viewer -> viewer : txtSearchID.getText()
viewer -> dao++ : searchForProduct(searchedID)

dao -> jdbc++ : getConnection(dbURL)
jdbc--> dao : connection
jdbc--

dao -> dao : prepareStatement(sql)
dao -> dao : setString(1, searchID)
dao -> dao : executeQuery()

dao -> dao : use getters to retrieve product attributes
dao -> dao : use setters to set product attributes
dao --> viewer : searchedProduct

dao--

' put products in Simple List Model
viewer -> modellist++ : updateItems(searchedProduct)
modellist--
viewer-- 

viewer --> user : awaiting next operation
@enduml
